### ISSUE TITLE
Add .ctp files to phinder analization target

### ISSUE THREAD

**Issue by nagaakihoshi** [sider/phinder#34]
Now phinder seems to analyze only `.php` files. However we have lots of `.ctp` files to be checked. So if you can, I hope you add new target in `autoload.php`

**Comment by tomokinakamaru** [comment]
Thank you for helping us! We will add the extension `.ctp` to the target set as soon as possible.

**Comment by tomokinakamaru** [comment]
We added *.ctp to Phinder's target. (https://github.com/sider/phinder/commit/0553233b5985374decc4944213ce73ed3fa409ab)

@nagaakihoshi Sorry for being late to notify this to you. Hope this helps!
