### ISSUE TITLE
Feature request: Return error code when `phinder` is failed

### ISSUE THREAD

**Issue by iainconnor** [sider/phinder#37]
Similar to https://github.com/sider/phinder/issues/15, I want to run this tool in a CI environment and block deploys if any of the rules fail.

Currently, even if there are internal errors or rule violations, exit code is `0`.

**Comment by tomokinakamaru** [comment]
@iainconnor This seems to be solved by your PR #38. Will you close this issue after your confirmation?

**Comment by iainconnor** [comment]
All good now! Thanks for the merge.

**Comment by iainconnor** [comment]
Any chance you could pay me back by tagging a release? The push before mine that updated the PHP parser version requirement is something I need to integrate this library.
