### ISSUE TITLE
Invalid pattern: `_` without paren as a receiver

### ISSUE THREAD

**Issue by wata727** [sider/phinder#45]
The following pattern is valid:

```
$ phinder -q '?->call(...)'
```

However, the following pattern is invalid:

```
$ phinder -q '_->call(...)'
Invalid pattern found in  in /tmp/phpQcmpw5: _->call(...)
```

As a workaround, we can use a wildcard pattern with paren.

```
$ phinder -q '(_)->call(...)'
# No errors
```

I think that the pattern should work correctly. What do you think?

**Comment by tomokinakamaru** [comment]
Thank you for reporting it, this is obviously a bug so I will fix it as soon as possible!
