### ISSUE TITLE
Incorrect requirements

### ISSUE THREAD

**Issue by Jeckerson** [sider/phinder#48]
In documentation there are requirements specification that are not correct:
`Phinder requires PHP >= 7.0`

But one of dependency - `symfony/yaml` requires `^7.1.3`

Example: 
`- symfony/yaml v4.2.3 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.`

**Comment by wata727** [comment]
Thanks for reporting this issue. Probably this is a bug for composer requirements.
Opened a pull request to resolve this problem #49

**Comment by tomokinakamaru** [comment]
@Jeckerson @wata727 Sorry for my late replying, I was "out-of-service" this week because of the flu I got :(

The pull request #49 seems to fix this problem. Does this work for you @Jeckerson? If it does, I will merge #49 and close this issue!

**Comment by Jeckerson** [comment]
@tomokinakamaru Hello! Yes it works, thank you!
